### ISSUE TITLE
container won't start due to error about @rock-id@

### ISSUE THREAD

**Issue by tombisho** [obiba/docker-rock#1]
I am trying to use the "standard" docker configuration listed in the Opal help https://opaldoc.obiba.org/en/latest/admin/installation.html#docker-image-installation

When I start the containers I see the error listed below. I reported it here because I could find the @rock-id@ in the application.yml file. 

```
2021-06-15 10:51:05,382 - ERROR - org.springframework.boot.SpringApplication - Application run failed
rock_1       | org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
rock_1       | found character '@' that cannot start any token. (Do not use @ for indentation)
rock_1       |  in 'reader', line 8, column 7:
rock_1       |       id: @rock_id@
rock_1       |           ^
rock_1       |
rock_1       |  at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:418)
rock_1       |  at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
rock_1       |  at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:586)
rock_1       |  at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
rock_1       |  at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
rock_1       |  at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:136)
rock_1       |  at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
rock_1       |  at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
rock_1       |  at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
rock_1       |  at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
rock_1       |  at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
rock_1       |  at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
rock_1       |  at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
rock_1       |  at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
rock_1       |  at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95)
rock_1       |  at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:134)
rock_1       |  at org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.getData(OriginTrackedYamlLoader.java:99)
rock_1       |  at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:512)
rock_1       |  at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:200)
rock_1       |  at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:164)
rock_1       |  at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:84)
rock_1       |  at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
rock_1       |  at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:45)
rock_1       |  at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:34)
rock_1       |  at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:102)
rock_1       |  at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:118)
rock_1       |  at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:82)
rock_1       |  at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:118)
rock_1       |  at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:230)
rock_1       |  at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:217)
rock_1       |  at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:88)
rock_1       |  at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:80)
rock_1       |  at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:100)
rock_1       |  at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:86)
rock_1       |  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:203)
rock_1       |  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:196)
rock_1       |  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:170)
rock_1       |  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:148)
rock_1       |  at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
rock_1       |  at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
rock_1       |  at java.util.ArrayList.forEach(ArrayList.java:1259)
rock_1       |  at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
rock_1       |  at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
rock_1       |  at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
rock_1       |  at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:362)
rock_1       |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
rock_1       |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
rock_1       |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
rock_1       |  at org.obiba.rock.Application.main(Application.java:26)
rock_1       |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
rock_1       |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
rock_1       |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
rock_1       |  at java.lang.reflect.Method.invoke(Method.java:498)
rock_1       |  at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
rock_1       |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
rock_1       |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
rock_1       |  at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
docker_rock_1 exited with code 1
```

**Comment by ymarcon** [comment]
I cannot reproduce and that issue is not supposed to happen because of this line:
https://github.com/obiba/docker-rock/blob/main/bin/first_run.sh#L21

You should see in the docker-compose logs the output of the first_run.sh script, something like:

```
rock_1  | [Info] ROCK_HOME=/srv
rock_1  | First run setup...
rock_1  | [Info] Applying config...
rock_1  | [Info] Node properties
rock_1  | [Warn]   Setting default node id: rserver
rock_1  | [Info]   Setting empty node tags
rock_1  | [Info] Consul properties
rock_1  | [Info]   No Consul server: self-registration not activated
rock_1  | [Warn]   No Consul token: self-registration not safe
rock_1  | [Info] Opal properties
rock_1  | [Info] R properties
rock_1  | [Info]   No R repositories, setting default
rock_1  | [Info] Users properties
rock_1  | [Info]   No manager configured!
rock_1  | [Info]   No user configured!
rock_1  | JAVA_OPTS=-Xmx2G
rock_1  | ROCK_HOME=/srv
rock_1  | ROCK_DIST=/usr/share/rock-1.0.3
rock_1  | 
rock_1  |      (                           (
rock_1  |      )\ )                  )     )\ )
rock_1  |     (()/(               ( /(    (()/(
rock_1  |      /(_))   (     (    )\())    /(_))
rock_1  |     (_))     )\    )\  ((_)\    (_))
rock_1  |     | _ \   ((_)  ((_) | |(_)   | _ \
rock_1  |     |   /  / _ \ / _|  | / /    |   /
rock_1  |     |_|_\  \___/ \__|  |_\_\    |_|_\
rock_1  | 
rock_1  |        .:: OBiBa Rock R server ::.
rock_1  | 
```

**Comment by kazoompa** [comment]
I had the similar issue after a server reboot, when I tried to start the exited docker I also had the following exception:

```
rock_1        | [Info] ROCK_HOME=/srv
rock_1        | JAVA_OPTS=-Xmx2G
rock_1        | ROCK_HOME=/srv
rock_1        | ROCK_DIST=/usr/share/rock-1.0.1
rock_1        | 2021-06-09 12:00:59,067 - ERROR - org.springframework.boot.SpringApplication - Application run failed
rock_1        | org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
rock_1        | found character '@' that cannot start any token. (Do not use @ for indentation)
rock_1        |  in 'reader', line 8, column 7:
rock_1        |       id: @rock_id@
rock_1        |           ^
rock_1        | 
rock_1        |  at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:418)
rock_1        |  at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
rock_1        |  at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:586)
rock_1        |  at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
rock_1        |  at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
rock_1        |  at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:136)
rock_1        |  at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
rock_1        |  at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
rock_1        |  at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
rock_1        |  at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
rock_1        |  at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
rock_1        |  at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
rock_1        |  at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
rock_1        |  at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
rock_1        |  at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95)
rock_1        |  at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:134)
rock_1        |  at org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.getData(OriginTrackedYamlLoader.java:99)
rock_1        |  at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:512)
rock_1        |  at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:200)
rock_1        |  at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:164)
rock_1        |  at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:84)
rock_1        |  at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
rock_1        |  at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:45)
rock_1        |  at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:34)
rock_1        |  at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:102)
rock_1        |  at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:118)
rock_1        |  at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:82)
rock_1        |  at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:118)
rock_1        |  at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:230)
rock_1        |  at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:217)
rock_1        |  at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:88)
rock_1        |  at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:80)
rock_1        |  at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:100)
rock_1        |  at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:86)
rock_1        |  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:203)
rock_1        |  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:196)
rock_1        |  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:170)
rock_1        |  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:148)
rock_1        |  at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
rock_1        |  at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
rock_1        |  at java.util.ArrayList.forEach(ArrayList.java:1259)
rock_1        |  at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
rock_1        |  at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
rock_1        |  at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
rock_1        |  at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:362)
rock_1        |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
rock_1        |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
rock_1        |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
rock_1        |  at org.obiba.rock.Application.main(Application.java:26)
rock_1        |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
rock_1        |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
rock_1        |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
rock_1        |  at java.lang.reflect.Method.invoke(Method.java:498)
rock_1        |  at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
rock_1        |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
rock_1        |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
rock_1        |  at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
docker-mlstr-r_rock_1 exited with code 1
```

**Comment by ymarcon** [comment]
So I guess the first_run.sh did not run because this condition was not verified:
https://github.com/obiba/docker-rock/blob/main/docker-entrypoint.sh#L15
despite the conf folder was recreated:
https://github.com/obiba/docker-rock/blob/main/docker-entrypoint.sh#L8

**Comment by tombisho** [comment]
Thanks for the pointer - so I deleted everything (images, volumes etc.) and started again. For my first run there was a problem with my Docker version so I guess that first_run.sh did not complete. This time everything went smoothly. I guess this can be closed then, unless it is still a problem for @kazoompa ?

**Comment by kazoompa** [comment]
At the moment if I stop and start rock container there are no problems. I know creating a new container is not a problem either. Maybe the server reboot killed the process in a way to cause this error!

**Comment by tombisho** [comment]
I think it is an unclean shutdown before first run that caused the problem. I will close for now. Thanks for input

**Comment by ymarcon** [comment]
Maybe the first_run.sh script could be reinstated when a new conf directory is created? Or would you prefer as an admin that we let the error go so that one get aware of the bad shutdown problem?
